$fg = rgba(e0def4ff)
$bg = rgba(191724ee)
$red = rgba(eb6f92ff)
$check = rgba(ebbcbaff)
$form_outer= rgba(343049ff)
$form_inner = rgba(252239ff)
$active_border = rgba(9ccfd8ee)
$inactive_border = rgba(434a4caa)
$shadow = rgba(1a1a1aee)