$fg = rgba(e0def4ff)
$bg = rgba(191724ee)
$red = rgba(eb6f92ff)
$check = rgba(ebbcbaff)
$form_outer= rgba(343049ff)
$form_inner = rgba(252239ff)
$active_border = rgba(9ccfd8ee)
$inactive_border = rgba(434a4caa)
$shadow = rgba(1a1a1aee)


# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 1
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 4
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    fade_on_empty = false
    rounding = 5
    placeholder_text =
    fail_text = error!
    check_color = $check
    fail_color = $red
    outer_color = $form_outer
    #outer_color = rgba(bdae93ff)
    inner_color = $form_inner
    font_color = $fg
    halign = center
    valign = center
}

# # DATE
# label {
#   monitor =
#   text = cmd[update:43200000] date +"%A, %d %B %Y"
#   font_size = 22
#   font_family = JetBrains Mono
#   position = 0, 300
#   halign = center
#   valign = center
# }

 # TIME
 label {
   monitor = 
   text = $TIME
   color = $fg
   font_size = 95
   font_family = Noto Serif Black
   position = 0, 200
   halign = center
   valign = center
 }