#preload = ~/Pictures/Wallpapers/boulevard.jpg
preload = "~/Pictures/Camera Roll/2024-2025 Level 5/PXL_20240812_195500474.MP.jpg"
wallpaper = "~/Pictures/Camera Roll/2024-2025 Level 5/PXL_20240812_195500474.MP.jpg"
