#!/bin/sh
REPO='/home/richard/Projects/Dotfiles/'
stow -d $REPO -t ~/ .

# sddm settings - copy from dotfiles to etc
if ! diff -q $REPO/.config/sddm/sddm.conf /etc/sddm.conf > /dev/null; then
  echo "Your SDDM dotfile and system file are out of sync!"
fi

cd $REPO